name: Auto-Rerun

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  auto-rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.run_attempt < 5 }}
    steps:
      - name: Trigger Re-run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TRIGGERING_REPOSITORY_ID: ${{ github.event.repository.id }}
          TRIGGERING_WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          gh api --method POST "repositories/$TRIGGERING_REPOSITORY_ID/actions/runs/$TRIGGERING_WORKFLOW_RUN_ID/rerun-failed-jobs"
