# This is a basic workflow to help you get started with Actions

name: Retry

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ context.payload.workflow_run.conclusion == 'failed' }}
        run: |
          curl -X POST --header "Authorization: token ${{ github.token }}" https://api.github.com/repos/test-org43834/retry-test/actions/runs/${{ context.payload.workflow_run.id }}/rerun
